version: '2'
services:
  app:
    build: ./fluentd
    container_name: app
    volumes:
      - ./log/events.log:/tmp/webhook-prototype-events.log
      - ./fluentd/etc:/fluentd/etc
  kafka:
    image: landoop/fast-data-dev:latest
    container_name: kafka
    environment:
      RUNTESTS: 0
    ports:
      - 2181:2181
      - 3030:3030
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092
  consumer:
    build: ./consumer
    container_name: consumer
    working_dir: /app
    command: bundle exec karafka s
    volumes:
      - ./consumer:/app
      - bundle_cache:/usr/local/bundle
volumes:
  bundle_cache:
